### ISSUE TITLE
Crashes with error TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by pastinepolenta** [edolyne/sanity-plugin-color-picker#3]
Crashes with error TypeError: Cannot read property 'focus' of undefined

at ColorPicker.focus (/static/js/app.bundle.js:275465:24)
    at ColorPicker.focus (/static/js/app.bundle.js:348798:25)
    at FormBuilderInput.focus (/static/js/app.bundle.js:34192:19)
    at FormBuilderInput.focus (/static/js/app.bundle.js:348798:25)
    at Field.focus (/static/js/app.bundle.js:203328:19)
    at Field.focus (/static/js/app.bundle.js:348798:25)
    at ObjectInput.focus (/static/js/app.bundle.js:202756:24)
    at ObjectInput.focus (/static/js/app.bundle.js:348798:25)
    at FormBuilderInput.focus (/static/js/app.bundle.js:34192:19)
    at FormBuilderInput.focus (/static/js/app.bundle.js:348798:25)

on the sanity studio

**Comment by npk-media-dev** [comment]
Got the same error, any luck with it?

**Comment by joshiefishbein** [comment]
Getting this error too. 

It happens only when nested inside of a collapsible object or fieldset that is collapsed by default. This makes sense with the error because the field that's trying focus doesn't exist yet, hence the `undefined`.

Plugin Version `1.0.3` on Sanity Studio Version `2.14.0`

**Comment by vin-ni** [comment]
Same problem here.

**Comment by jaredshaunsmith** [comment]
Fixed in this PR https://github.com/edolyne/sanity-plugin-color-picker/pull/4 - would love a merge here

**Comment by asse15131c** [comment]
Hi @edolyne,

I noticed that this pr was merged but not published on NPM.
Would you please publish this fix? 🙏 

Thank you so much!
